#!/bin/bash

# Make sure the user data directory is owned by the developer user
#if [ -d /home/developer/.eclipse ]; then
#  sudo chown developer:developer /home/developer/.eclipse
#fi

/opt/eclipse/eclipse \
  -user /home/developer \
  -configuration /home/developer/.eclipse \
  -data /home/developer/workspace
  
